In [108]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)

In [109]:
matches = pd.read_csv('E:\IPL_Win_Probability_Predictor\data\matches_updated_ipl_upto_2025.csv')
deliveries = pd.read_csv('E:\IPL_Win_Probability_Predictor\data\deliveries_updated_ipl_upto_2025.csv')

In [110]:
matches.head()

,season,venue,event,winner_runs,umpire2,toss_winner,date,neutralvenue,umpire1,city,reserve_umpire,winner,eliminator,date1,method,team1,toss_decision,gender,team2,balls_per_over,winner_wickets,tv_umpire,player_of_match,match_referee,outcome,date2,match_number,matchId
0,2007/08,M Chinnaswamy Stadium,Indian Premier League,140.0,RE Koertzen,Royal Challengers Bangalore,2008-04-18,NaN,Asad Rauf,Bangalore,VN Kulkarni,Kolkata Knight Riders,NaN,NaN,NaN,Royal Challengers Bangalore,field,male,Kolkata Knight Riders,6,NaN,AM Saheba,BB McCullum,J Srinath,NaN,NaN,1.0,335982
1,2007/08,"Punjab Cricket Association Stadium, Mohali",Indian Premier League,33.0,SL Shastri,Chennai Super Kings,2008-04-19,NaN,MR Benson,Chandigarh,MSS Ranawat,Chennai Super Kings,NaN,NaN,NaN,Kings XI Punjab,bat,male,Chennai Super Kings,6,NaN,RB Tiffin,MEK Hussey,S Venkataraghavan,NaN,NaN,2.0,335983
2,2007/08,Feroz Shah Kotla,Indian Premier League,NaN,GA Pratapkumar,Rajasthan Royals,2008-04-19,NaN,Aleem Dar,Delhi,NaN,Delhi Daredevils,NaN,NaN,NaN,Delhi Daredevils,bat,male,Rajasthan Royals,6,9.0,IL Howell,MF Maharoof,GR Viswanath,NaN,NaN,3.0,335984
3,2007/08,Eden Gardens,Indian Premier League,NaN,K Hariharan,Deccan Chargers,2008-04-20,NaN,BF Bowden,Kolkata,F Gomes,Kolkata Knight Riders,NaN,NaN,NaN,Kolkata Knight Riders,bat,male,Deccan Chargers,6,5.0,Asad Rauf,DJ Hussey,FM Engineer,NaN,NaN,4.0,335986
4,2007/08,Wankhede Stadium,Indian Premier League,NaN,DJ Harper,Mumbai Indians,2008-04-20,NaN,SJ Davis,Mumbai,SN Bandekar,Royal Challengers Bangalore,NaN,NaN,NaN,Mumbai Indians,bat,male,Royal Challengers Bangalore,6,5.0,AV Jayaprakash,MV Boucher,J Srinath,NaN,NaN,5.0,335985

In [111]:
deliveries.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2008-04-18
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18

In [112]:
print("Matches Shape:",matches.shape)
print("Deliveries Shape:",deliveries.shape)

Matches Shape: (1169, 28)
Deliveries Shape: (278205, 20)

In [113]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           1169 non-null   object
 1   venue            1169 non-null   object
 2   event            1169 non-null   object
 3   winner_runs      531 non-null    float64
 4   umpire2          1169 non-null   object
 5   toss_winner      1169 non-null   object
 6   date             1169 non-null   object
 7   neutralvenue     77 non-null     object
 8   umpire1          1169 non-null   object
 9   city             1118 non-null   object
 10  reserve_umpire   1145 non-null   object
 11  winner           1146 non-null   object
 12  eliminator       15 non-null     object
 13  date1            2 non-null      object
 14  method           19 non-null     object
 15  team1            1169 non-null   object
 16  toss_decision    1169 non-null   object
 17  gender           1169 non-null   object
 18  team2            1169 non-null   object
 19  balls_per_over   1169 non-null   int64
 20  winner_wickets   615 non-null    float64
 21  tv_umpire        1165 non-null   object
 22  player_of_match  1161 non-null   object
 23  match_referee    1169 non-null   object
 24  outcome          23 non-null     object
 25  date2            2 non-null      object
 26  match_number     1099 non-null   float64
 27  matchId          1169 non-null   int64
dtypes: float64(3), int64(2), object(23)
memory usage: 255.8+ KB

In [114]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchId           278205 non-null  int64
 1   inning            278205 non-null  int64
 2   over_ball         278205 non-null  float64
 3   over              278205 non-null  int64
 4   ball              278205 non-null  int64
 5   batting_team      278205 non-null  object
 6   bowling_team      278205 non-null  object
 7   batsman           278205 non-null  object
 8   non_striker       278205 non-null  object
 9   bowler            278205 non-null  object
 10  batsman_runs      278205 non-null  int64
 11  extras            278205 non-null  int64
 12  isWide            9080 non-null    float64
 13  isNoBall          1163 non-null    float64
 14  Byes              701 non-null     float64
 15  LegByes           4215 non-null    float64
 16  Penalty           2 non-null       float64
 17  dismissal_kind    13823 non-null   object
 18  player_dismissed  13823 non-null   object
 19  date              278205 non-null  object
dtypes: float64(6), int64(6), object(8)
memory usage: 42.5+ MB

In [115]:
matches.isnull().sum()

season                0
venue                 0
event                 0
winner_runs         638
umpire2               0
toss_winner           0
date                  0
neutralvenue       1092
umpire1               0
city                 51
reserve_umpire       24
winner               23
eliminator         1154
date1              1167
method             1150
team1                 0
toss_decision         0
gender                0
team2                 0
balls_per_over        0
winner_wickets      554
tv_umpire             4
player_of_match       8
match_referee         0
outcome            1146
date2              1167
match_number         70
matchId               0
dtype: int64

In [116]:
deliveries.isnull().sum()

matchId                  0
inning                   0
over_ball                0
over                     0
ball                     0
batting_team             0
bowling_team             0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extras                   0
isWide              269125
isNoBall            277042
Byes                277504
LegByes             273990
Penalty             278203
dismissal_kind      264382
player_dismissed    264382
date                     0
dtype: int64

In [117]:
matches[['matchId',
         'season',
         'team1',
         'team2',
         'winner',
         'venue']].head()

,matchId,season,team1,team2,winner,venue
0,335982,2007/08,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,M Chinnaswamy Stadium
1,335983,2007/08,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali"
2,335984,2007/08,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,Feroz Shah Kotla
3,335986,2007/08,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,Eden Gardens
4,335985,2007/08,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,Wankhede Stadium

In [118]:
deliveries[['matchId',
            'inning',
            'over',
            'ball',
            'batting_team',
            'bowling_team']].head()

,matchId,inning,over,ball,batting_team,bowling_team
0,335982,1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,0,2,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,0,3,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,0,4,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,0,5,Kolkata Knight Riders,Royal Challengers Bangalore

In [119]:
matches['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022',
       '2023', '2024', '2025'], dtype=object)

In [120]:
matches['season'].nunique()

18

In [121]:
teams1 = matches['team1'].unique()
teams2 = matches['team2'].unique()

all_teams = set(teams1).union(set(teams2))
print(sorted(all_teams))

['Chennai Super Kings', 'Deccan Chargers', 'Delhi Capitals', 'Delhi Daredevils', 'Gujarat Lions', 'Gujarat Titans', 'Kings XI Punjab', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiant', 'Rising Pune Supergiants', 'Royal Challengers Bangalore', 'Royal Challengers Bengaluru', 'Sunrisers Hyderabad']

In [122]:
matches['winner'].value_counts()

winner
Mumbai Indians                 151
Chennai Super Kings            142
Kolkata Knight Riders          135
Royal Challengers Bangalore    114
Rajasthan Royals               114
Sunrisers Hyderabad             93
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  51
Gujarat Titans                  37
Punjab Kings                    34
Lucknow Super Giants            30
Deccan Chargers                 29
Royal Challengers Bengaluru     18
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [123]:
matches_clean = matches[
    ['matchId',
     'season',
     'team1',
     'team2',
     'winner',
     'venue']
    ].copy()

In [124]:
matches_clean.head()

,matchId,season,team1,team2,winner,venue
0,335982,2007/08,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,M Chinnaswamy Stadium
1,335983,2007/08,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali"
2,335984,2007/08,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,Feroz Shah Kotla
3,335986,2007/08,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,Eden Gardens
4,335985,2007/08,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,Wankhede Stadium

In [125]:
team_mapping = {
    'Delhi Daredevils' : 'Delhi Capitals',
    'Kings XI Punjab' : 'Punjab Kings',
    'Royal Challengers Bangalore' : 'Royal Challengers Bengaluru',
    'Rising Pune Supergiant' : 'Rising Pune Supergiants'
}

In [126]:
matches_clean['team1'] = matches_clean['team1'].replace(team_mapping)
matches_clean['team2'] = matches_clean['team2'].replace(team_mapping)
matches_clean['winner'] = matches_clean['winner'].replace(team_mapping)

In [127]:
deliveries['batting_team'] = deliveries['batting_team'].replace(team_mapping)
deliveries['bowling_team'] = deliveries['bowling_team'].replace(team_mapping)

In [128]:
teams1 = matches_clean['team1'].unique()
teams2 = matches_clean['team2'].unique()

all_teams = set(teams1).union(set(teams2))
print(sorted(all_teams))

['Chennai Super Kings', 'Deccan Chargers', 'Delhi Capitals', 'Gujarat Lions', 'Gujarat Titans', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiants', 'Royal Challengers Bengaluru', 'Sunrisers Hyderabad']

In [129]:
current_teams = [
    'Chennai Super Kings',
    'Delhi Capitals',
    'Gujarat Titans',
    'Kolkata Knight Riders',
    'Lucknow Super Giants',
    'Mumbai Indians',
    'Punjab Kings',
    'Rajasthan Royals',
    'Royal Challengers Bengaluru',
    'Sunrisers Hyderabad'
]

In [130]:
matches_clean = matches_clean[
    matches_clean['team1'].isin(current_teams)
]

In [131]:
matches_clean = matches_clean[
    matches_clean['team2'].isin(current_teams)
]

In [132]:
sorted(
    set(matches_clean['team1'].unique())
)

['Chennai Super Kings',
 'Delhi Capitals',
 'Gujarat Titans',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Punjab Kings',
 'Rajasthan Royals',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [133]:
matches_clean.shape

(984, 6)

In [134]:
venues = sorted(matches_clean['venue'].dropna().unique())

for venue in venues:
    print(venue)

Arun Jaitley Stadium
Arun Jaitley Stadium, Delhi
Barabati Stadium
Barsapara Cricket Stadium, Guwahati
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow
Brabourne Stadium
Brabourne Stadium, Mumbai
Buffalo Park
De Beers Diamond Oval
Dr DY Patil Sports Academy
Dr DY Patil Sports Academy, Mumbai
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam
Dubai International Cricket Stadium
Eden Gardens
Eden Gardens, Kolkata
Feroz Shah Kotla
Himachal Pradesh Cricket Association Stadium
Himachal Pradesh Cricket Association Stadium, Dharamsala
Holkar Cricket Stadium
JSCA International Stadium Complex
Kingsmead
M Chinnaswamy Stadium
M Chinnaswamy Stadium, Bengaluru
M.Chinnaswamy Stadium
MA Chidambaram Stadium
MA Chidambaram Stadium, Chepauk
MA Chidambaram Stadium, Chepauk, Chennai
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh
Maharashtra Cricket Association Stadium
Maharashtra Cricket Association Stadium, Pune
Narendra Modi Stadium, Ahmedabad
New Wanderers Stadium
Newlands
OUTsurance Oval
Punjab Cricket Association IS Bindra Stadium
Punjab Cricket Association IS Bindra Stadium, Mohali
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh
Punjab Cricket Association Stadium, Mohali
Rajiv Gandhi International Stadium
Rajiv Gandhi International Stadium, Uppal
Rajiv Gandhi International Stadium, Uppal, Hyderabad
Sardar Patel Stadium, Motera
Sawai Mansingh Stadium
Sawai Mansingh Stadium, Jaipur
Shaheed Veer Narayan Singh International Stadium
Sharjah Cricket Stadium
Sheikh Zayed Stadium
St George's Park
Subrata Roy Sahara Stadium
SuperSport Park
Wankhede Stadium
Wankhede Stadium, Mumbai
Zayed Cricket Stadium, Abu Dhabi

In [135]:
venue_mapping = {

    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',

    'Brabourne Stadium, Mumbai': 'Brabourne Stadium',

    'Eden Gardens, Kolkata': 'Eden Gardens',

    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',

    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',

    'Punjab Cricket Association IS Bindra Stadium, Mohali':
        'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh':
        'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association Stadium, Mohali':
        'Punjab Cricket Association IS Bindra Stadium',

    'Rajiv Gandhi International Stadium, Uppal':
        'Rajiv Gandhi International Stadium',

    'Rajiv Gandhi International Stadium, Uppal, Hyderabad':
        'Rajiv Gandhi International Stadium',
    
    'Sawai Mansingh Stadium, Jaipur':
        'Sawai Mansingh Stadium',

    'Narendra Modi Stadium, Ahmedabad':
        'Narendra Modi Stadium',
    
    'Sardar Patel Stadium, Motera':
        'Narendra Modi Stadium',
    
    'Himachal Pradesh Cricket Association Stadium, Dharamsala':
        'Himachal Pradesh Cricket Association Stadium',

    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam':
        'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',

    'Wankhede Stadium, Mumbai':
        'Wankhede Stadium',

    'Dr DY Patil Sports Academy, Mumbai':
        'Dr DY Patil Sports Academy',

    'Maharashtra Cricket Association Stadium, Pune':
        'Maharashtra Cricket Association Stadium',

    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh':
        'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur'
}

In [136]:
matches_clean['venue'] = matches_clean['venue'].replace(venue_mapping)

In [137]:
len(sorted(matches_clean['venue'].dropna().unique()))

35

In [138]:
venues = sorted(matches_clean['venue'].dropna().unique())
for venue in venues:
    print(venue)

Arun Jaitley Stadium
Barabati Stadium
Barsapara Cricket Stadium, Guwahati
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow
Brabourne Stadium
Buffalo Park
De Beers Diamond Oval
Dr DY Patil Sports Academy
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium
Dubai International Cricket Stadium
Eden Gardens
Feroz Shah Kotla
Himachal Pradesh Cricket Association Stadium
Holkar Cricket Stadium
JSCA International Stadium Complex
Kingsmead
M Chinnaswamy Stadium
MA Chidambaram Stadium
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur
Maharashtra Cricket Association Stadium
Narendra Modi Stadium
New Wanderers Stadium
Newlands
OUTsurance Oval
Punjab Cricket Association IS Bindra Stadium
Rajiv Gandhi International Stadium
Sawai Mansingh Stadium
Shaheed Veer Narayan Singh International Stadium
Sharjah Cricket Stadium
Sheikh Zayed Stadium
St George's Park
Subrata Roy Sahara Stadium
SuperSport Park
Wankhede Stadium
Zayed Cricket Stadium, Abu Dhabi

In [139]:
deliveries.columns.tolist()

['matchId',
 'inning',
 'over_ball',
 'over',
 'ball',
 'batting_team',
 'bowling_team',
 'batsman',
 'non_striker',
 'bowler',
 'batsman_runs',
 'extras',
 'isWide',
 'isNoBall',
 'Byes',
 'LegByes',
 'Penalty',
 'dismissal_kind',
 'player_dismissed',
 'date']

In [140]:
deliveries['total_run'] = (
    deliveries['batsman_runs']+deliveries['extras']
)

In [141]:
first_inning = deliveries[deliveries['inning']==1]

In [142]:
first_inning.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bengaluru,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2008-04-18,1
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,0
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,1
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,0
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,0

In [143]:
target_df = (
    first_inning.groupby('matchId')['total_run'].sum().reset_index()
)

In [144]:
target_df['target'] = (
    target_df['total_run']+1
)

In [145]:
target_df.head()

   matchId  total_run  target
0   335982        222     223
1   335983        240     241
2   335984        129     130
3   335985        165     166
4   335986        110     111

In [146]:
match_df = matches_clean.merge(
    target_df[['matchId', 'target']],
    on = 'matchId'
)

In [147]:
match_df.head()

,matchId,season,team1,team2,winner,venue,target
0,335982,2007/08,Royal Challengers Bengaluru,Kolkata Knight Riders,Kolkata Knight Riders,M Chinnaswamy Stadium,223
1,335983,2007/08,Punjab Kings,Chennai Super Kings,Chennai Super Kings,Punjab Cricket Association IS Bindra Stadium,241
2,335984,2007/08,Delhi Capitals,Rajasthan Royals,Delhi Capitals,Feroz Shah Kotla,130
3,335985,2007/08,Mumbai Indians,Royal Challengers Bengaluru,Royal Challengers Bengaluru,Wankhede Stadium,166
4,335987,2007/08,Rajasthan Royals,Punjab Kings,Rajasthan Royals,Sawai Mansingh Stadium,167

In [148]:
match_df.shape

(984, 7)

In [149]:
second_inning = deliveries[
    deliveries['inning']==2
].copy()

In [150]:
second_inning.shape

(133903, 21)

In [151]:
second_inning = second_inning.merge(
    match_df[['matchId','target']],
    on = 'matchId'
)

In [152]:
second_inning.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,target
0,335982,2,0.1,0,1,Royal Challengers Bengaluru,Kolkata Knight Riders,R Dravid,W Jaffer,AB Dinda,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,1,223
1,335982,2,0.2,0,2,Royal Challengers Bengaluru,Kolkata Knight Riders,W Jaffer,R Dravid,AB Dinda,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,1,223
2,335982,2,0.3,0,3,Royal Challengers Bengaluru,Kolkata Knight Riders,W Jaffer,R Dravid,AB Dinda,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,0,223
3,335982,2,0.4,0,4,Royal Challengers Bengaluru,Kolkata Knight Riders,W Jaffer,R Dravid,AB Dinda,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,1,223
4,335982,2,0.5,0,5,Royal Challengers Bengaluru,Kolkata Knight Riders,R Dravid,W Jaffer,AB Dinda,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18,1,223

In [153]:
second_inning['current_score'] = (
    second_inning.groupby('matchId')['total_run'].cumsum()
)

In [154]:
second_inning[['matchId','total_run','current_score']].head(20)

    matchId  total_run  current_score
0    335982          1              1
1    335982          1              2
2    335982          0              2
3    335982          1              3
4    335982          1              4
5    335982          0              4
6    335982          0              4
7    335982          0              4
8    335982          0              4
9    335982          4              8
10   335982          1              9
11   335982          0              9
12   335982          0              9
13   335982          0              9
14   335982          0              9
15   335982          1             10
16   335982          0             10
17   335982          1             11
18   335982          0             11
19   335982          1             12

In [155]:
second_inning['runs_left'] = (
    second_inning['target'] - second_inning['current_score']
)

In [156]:
second_inning[['target','current_score','runs_left']].head()

   target  current_score  runs_left
0     223              1        222
1     223              2        221
2     223              2        221
3     223              3        220
4     223              4        219

In [157]:
second_inning['balls_bowled'] = (
    second_inning['over']*6 + second_inning['ball']
)

In [158]:
second_inning['balls_left'] = (
    120 - second_inning['balls_bowled']
)

In [159]:
second_inning[
    ['over', 'ball', 'balls_bowled', 'balls_left']
    ].head(20)

    over  ball  balls_bowled  balls_left
0      0     1             1         119
1      0     2             2         118
2      0     3             3         117
3      0     4             4         116
4      0     5             5         115
5      0     6             6         114
6      0     7             7         113
7      1     1             7         113
8      1     2             8         112
9      1     3             9         111
10     1     4            10         110
11     1     5            11         109
12     1     6            12         108
13     2     1            13         107
14     2     2            14         106
15     2     3            15         105
16     2     4            16         104
17     2     5            17         103
18     2     6            18         102
19     2     7            19         101

In [160]:
second_inning['player_dismissed'] = (
    second_inning['player_dismissed'].notna().astype(int)
)

In [161]:
second_inning['wickets_fallen'] = (
    second_inning.groupby('matchId')['player_dismissed'].cumsum()
)

In [162]:
second_inning[['player_dismissed','wickets_fallen']].head(50)

    player_dismissed  wickets_fallen
0                  0               0
1                  0               0
2                  0               0
3                  0               0
4                  0               0
5                  0               0
6                  0               0
7                  1               1
8                  0               1
9                  0               1
10                 0               1
11                 0               1
12                 0               1
13                 0               1
14                 1               2
15                 0               2
16                 0               2
17                 0               2
18                 0               2
19                 0               2
20                 0               2
21                 0               2
22                 0               2
23                 0               2
24                 0               2
25                 0               2
26                 0               2
27                 0               2
28                 0               2
29                 0               2
30                 1               3
31                 0               3
32                 0               3
33                 1               4
34                 0               4
35                 0               4
36                 0               4
37                 0               4
38                 0               4
39                 0               4
40                 0               4
41                 0               4
42                 0               4
43                 0               4
44                 0               4
45                 0               4
46                 0               4
47                 0               4
48                 0               4
49                 0               4

In [163]:
second_inning['wickets_left'] = (
    10 - second_inning['wickets_fallen']
)

In [164]:
second_inning['crr'] = (second_inning['current_score']*6)/(120 - second_inning['balls_left'])

In [165]:
second_inning['rrr'] = (second_inning['runs_left']*6)/(second_inning['balls_left'])

In [166]:
second_inning[
[
'target',
'current_score',
'runs_left',
'balls_left',
'wickets_left',
'crr',
'rrr'
]
].head(10)

,target,current_score,runs_left,balls_left,wickets_left,crr,rrr
0,223,1,222,119,10,6.000000,11.193277
1,223,2,221,118,10,6.000000,11.237288
2,223,2,221,117,10,4.000000,11.333333
3,223,3,220,116,10,4.500000,11.379310
4,223,4,219,115,10,4.800000,11.426087
5,223,4,219,114,10,4.000000,11.526316
6,223,4,219,113,10,3.428571,11.628319
7,223,4,219,113,9,3.428571,11.628319
8,223,4,219,112,9,3.000000,11.732143
9,223,8,215,111,9,5.333333,11.621622

In [167]:
second_inning = second_inning.merge(
    match_df[
        ['matchId','winner','venue']
    ],
    on= 'matchId'
)

In [168]:
second_inning.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date,total_run,target,current_score,runs_left,balls_bowled,balls_left,wickets_fallen,wickets_left,crr,rrr,winner,venue
0,335982,2,0.1,0,1,Royal Challengers Bengaluru,Kolkata Knight Riders,R Dravid,W Jaffer,AB Dinda,1,0,NaN,NaN,NaN,NaN,NaN,NaN,0,2008-04-18,1,223,1,222,1,119,0,10,6.0,11.193277,Kolkata Knight Riders,M Chinnaswamy Stadium
1,335982,2,0.2,0,2,Royal Challengers Bengaluru,Kolkata Knight Riders,W Jaffer,R Dravid,AB Dinda,0,1,1.0,NaN,NaN,NaN,NaN,NaN,0,2008-04-18,1,223,2,221,2,118,0,10,6.0,11.237288,Kolkata Knight Riders,M Chinnaswamy Stadium
2,335982,2,0.3,0,3,Royal Challengers Bengaluru,Kolkata Knight Riders,W Jaffer,R Dravid,AB Dinda,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,2008-04-18,0,223,2,221,3,117,0,10,4.0,11.333333,Kolkata Knight Riders,M Chinnaswamy Stadium
3,335982,2,0.4,0,4,Royal Challengers Bengaluru,Kolkata Knight Riders,W Jaffer,R Dravid,AB Dinda,1,0,NaN,NaN,NaN,NaN,NaN,NaN,0,2008-04-18,1,223,3,220,4,116,0,10,4.5,11.379310,Kolkata Knight Riders,M Chinnaswamy Stadium
4,335982,2,0.5,0,5,Royal Challengers Bengaluru,Kolkata Knight Riders,R Dravid,W Jaffer,AB Dinda,1,0,NaN,NaN,NaN,NaN,NaN,NaN,0,2008-04-18,1,223,4,219,5,115,0,10,4.8,11.426087,Kolkata Knight Riders,M Chinnaswamy Stadium

In [169]:
second_inning['result'] = np.where(
    second_inning['batting_team'] == second_inning['winner'],1,0
)

In [170]:
second_inning[['batting_team', 'winner', 'result']].head(20)

                   batting_team                 winner  result
0   Royal Challengers Bengaluru  Kolkata Knight Riders       0
1   Royal Challengers Bengaluru  Kolkata Knight Riders       0
2   Royal Challengers Bengaluru  Kolkata Knight Riders       0
3   Royal Challengers Bengaluru  Kolkata Knight Riders       0
4   Royal Challengers Bengaluru  Kolkata Knight Riders       0
5   Royal Challengers Bengaluru  Kolkata Knight Riders       0
6   Royal Challengers Bengaluru  Kolkata Knight Riders       0
7   Royal Challengers Bengaluru  Kolkata Knight Riders       0
8   Royal Challengers Bengaluru  Kolkata Knight Riders       0
9   Royal Challengers Bengaluru  Kolkata Knight Riders       0
10  Royal Challengers Bengaluru  Kolkata Knight Riders       0
11  Royal Challengers Bengaluru  Kolkata Knight Riders       0
12  Royal Challengers Bengaluru  Kolkata Knight Riders       0
13  Royal Challengers Bengaluru  Kolkata Knight Riders       0
14  Royal Challengers Bengaluru  Kolkata Knight Riders       0
15  Royal Challengers Bengaluru  Kolkata Knight Riders       0
16  Royal Challengers Bengaluru  Kolkata Knight Riders       0
17  Royal Challengers Bengaluru  Kolkata Knight Riders       0
18  Royal Challengers Bengaluru  Kolkata Knight Riders       0
19  Royal Challengers Bengaluru  Kolkata Knight Riders       0

In [171]:
final_df = second_inning[
    [
        'batting_team',
        'bowling_team',
        'venue',
        'runs_left',
        'balls_left',
        'wickets_left',
        'target',
        'crr',
        'rrr',
        'result'
    ]
]

In [172]:
final_df.head()

,batting_team,bowling_team,venue,runs_left,balls_left,wickets_left,target,crr,rrr,result
0,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,222,119,10,223,6.0,11.193277,0
1,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,221,118,10,223,6.0,11.237288,0
2,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,221,117,10,223,4.0,11.333333,0
3,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,220,116,10,223,4.5,11.379310,0
4,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,219,115,10,223,4.8,11.426087,0

In [173]:
final_df = final_df[final_df['balls_left']>0]

In [174]:
final_df = final_df[final_df['runs_left']>=0]

In [175]:
final_df.shape

(111948, 10)

In [176]:
final_df['result'].value_counts()

result
1    57085
0    54863
Name: count, dtype: int64

In [177]:
final_df.isnull().sum()

batting_team    0
bowling_team    0
venue           0
runs_left       0
balls_left      0
wickets_left    0
target          0
crr             0
rrr             0
result          0
dtype: int64

In [178]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [179]:
x = final_df.drop('result',axis = 1)
y = final_df['result']

In [180]:
x.head()

,batting_team,bowling_team,venue,runs_left,balls_left,wickets_left,target,crr,rrr
0,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,222,119,10,223,6.0,11.193277
1,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,221,118,10,223,6.0,11.237288
2,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,221,117,10,223,4.0,11.333333
3,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,220,116,10,223,4.5,11.379310
4,Royal Challengers Bengaluru,Kolkata Knight Riders,M Chinnaswamy Stadium,219,115,10,223,4.8,11.426087

In [181]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: result, dtype: int64

In [182]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [183]:
print(x_train.shape)
print(x_test.shape)

(89558, 9)
(22390, 9)

In [184]:
trf = ColumnTransformer(
    [
        (
            'trf',OneHotEncoder(handle_unknown='ignore'),
            ['batting_team','bowling_team','venue']
        )
    ],
    remainder = 'passthrough'
)

In [185]:
pipe = Pipeline(
    [
        ('step1',trf),
        ('step2',LogisticRegression(
            max_iter=3000
        ))
    ]
)

In [186]:
pipe.fit(
    x_train,
    y_train
)

C:\Users\ersar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 3000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=3000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue'])])),
                ('step2', LogisticRegression(max_iter=3000))])

In [187]:
y_pred = pipe.predict(x_test)

In [188]:
accuracy_score(
    y_test,
    y_pred
)

0.807815989280929

In [189]:
from sklearn.metrics import confusion_matrix

confusion_matrix(
    y_test,
    y_pred
)

array([[8660, 2291],
       [2012, 9427]])

In [190]:
from sklearn.ensemble import RandomForestClassifier

In [191]:
rf_pipe = Pipeline(
    [
        ('step1',trf),
        ('step2',RandomForestClassifier(
            n_estimators = 200,
            max_depth = 15,
            random_state = 42,
            n_jobs = -1
        ))
    ]
)

In [192]:
rf_pipe.fit(x_train, y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue'])])),
                ('step2',
                 RandomForestClassifier(max_depth=15, n_estimators=200,
                                        n_jobs=-1, random_state=42))])

In [193]:
rf_pred = rf_pipe.predict(x_test)

In [194]:
from sklearn.metrics import accuracy_score
rf_accuracy = accuracy_score(
    y_test,
    rf_pred
)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.9438588655649843

In [195]:
from sklearn.metrics import confusion_matrix

confusion_matrix(
    y_test,
    rf_pred
)

array([[10194,   757],
       [  500, 10939]])

In [196]:
from xgboost import XGBClassifier

In [197]:
xgb_pipe = Pipeline([
    ('step1',trf),
    ('step2',XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric='logloss'))
])

In [198]:
xgb_pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue'])])),
                ('step2',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=0.8, device=None,
                               early_stopping_rounds=None,
                               enable_...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [199]:
xgb_pred = xgb_pipe.predict(x_test)

In [200]:
from sklearn.metrics import accuracy_score

xgb_accuracy = accuracy_score(
    y_test,
    xgb_pred
)

print("XGBoost Accuracy:", xgb_accuracy)

XGBoost Accuracy: 0.9627958910227781

In [201]:
from sklearn.metrics import confusion_matrix

confusion_matrix(
    y_test,
    xgb_pred
)

array([[10489,   462],
       [  371, 11068]])

In [202]:
xgb_pipe.predict_proba(x_test[:5])

array([[0.02868652, 0.9713135 ],
       [0.95114857, 0.04885142],
       [0.74686784, 0.25313216],
       [0.1215297 , 0.8784703 ],
       [0.9622518 , 0.03774819]], dtype=float32)

In [207]:
import pickle

pickle.dump(xgb_pipe, open('models/xgb_pipe.pkl','wb'))

In [208]:
teams = sorted(final_df['batting_team'].unique())
venues = sorted(final_df['venue'].unique())

pickle.dump(teams, open('models/teams.pkl', 'wb'))
pickle.dump(venues, open('models/venues.pkl', 'wb'))

In [209]:
import os

os.listdir('models')

['.ipynb_checkpoints', 'teams.pkl', 'venues.pkl', 'xgb_pipe.pkl']